/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarComp: typeof import('./src/components/BarComp.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScatterChart: typeof import('./src/components/ScatterChart.vue')['default']
    SliderChart: typeof import('./src/components/SliderChart.vue')['default']
    SucPie: typeof import('./src/components/SucPie.vue')['default']
  }
}
